name: Bluetooth Mesh to MQTT
version: 0.1.29
slug: blemesh2mqtt
# Trigger GHCR package build with GHCR_TOKEN
image: ghcr.io/nitrokart/{arch}-blemesh2mqtt
description: Bridge Bluetooth Mesh lights (e.g. Ledvance) to Home Assistant via MQTT
arch:
  - aarch64
  - amd64
init: false
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW
apparmor: false
ingress: true
panel_icon: mdi:bluetooth
panel_title: BLE Mesh
services:
  - mqtt:want
options:
  adapter: 0
  io: auto
  log_level: info
schema:
  adapter: int(0,9)
  io: list(auto|generic|mgmt)
  log_level: list(debug|info|warning|error)
